server:
  port: 8081
spring:
  profiles: default
  application:
    name: StudentData
  datasource:
   password: root
   username: root
   url: jdbc:mysql://localhost:3306/studentdetails
   driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
   hibernate:
    ddl-auto: none
   show-sql: true       
  
  
